# @package __global__

defaults:
  - ../eval.yaml
  - skeleton.yaml

model_suffix: pretrained

# please make sure if you have downloaded the checkpoint
checkpoint: wm_ckpts/silent_cipher/16_khz/97561_iteration

dataset:
  eval_seg_duration: 4.5